# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/elastifile/emanage-go"
  branch = "import-paths"

[prune]
  go-tests = true
  unused-packages = true

